dyng/ctrlsf.vim

- autoload/ctrlsf.vim
- doc/ctrlsf.txt
- plugin/ctrlsf.vim
*   Use `g:ctrlsf_position` to specify one of `left`, `right`, `top`, or
`bottom`.
*   Use `g:ctrlsf_winsize` to specify size
> Support for horizontal splits.

- autoload/ctrlsf.vim
if winfixheight is not set, ':wincmd =' will equallize heights of all
windows. This makes 'g:ctrlsf_winsize` not works as expected when window
is splitted horizontally.
> set winfixheight for main and preview window

- after/plugin/ctrlsf.vim
> Reloading guard for 'after/plugin/ctrlsf.vim'

- autoload/ctrlsf/db.vim
Fix a bug in parsing process can cause missing of first line in each paragraph.
> Fix bug in result parsing

- autoload/ctrlsf/opt.vim
Main goal of this commit is to fix error in :CtrlSFOpen for fresh opened vim where no search has ever been invoked.
> Return empty as default value of argument

- autoload/ctrlsf/backend.vim
- autoload/ctrlsf/opt.vim
Hotfix for #86 .
The true reason for this issue is missing of `shellescape` for values of `--ignore-dir`.
> Fix missing of escaping for '--ignore-dir'

- autoload/ctrlsf.vim
Pretty simple addition but makes navigating splits with the quick fix window results a little easier.
> Allow quickfix window to occupy the full Vim width

- autoload/ctrlsf/edit.vim
> Save file for 'y' or 'enter', cancel for 'escape'.

- autoload/ctrlsf.vim
- autoload/ctrlsf/backend.vim
- plugin/ctrlsf.vim
Predefined error log file's path is not compatible with windows platform.
Issue reported by #124 .
> Use builtin method tempname() instead

- autoload/ctrlsf/backend.vim
Since `rg` does not support long version of context argument (e.g. `--after`, `--before`, `--context`), use short version instead.
> Use short context argument

- autoload/ctrlsf/class/paragraph.vim
Use relative path as a filename by default. 
FIx #147 .
> Use relative path as filename if possible

- autoload/ctrlsf/win.vim
This is a crude but simple way to cleanly detect when this is the last window, and then instead delete the buffer. 
It works fine on gvim on Windows and vim on Termux (both version 8), I still have to test this in Ubuntu with vim 7.3 (how far do you support vim?) I also didn't see any test suite, any expectations on testing? 
Should be otherwise pretty straightforward :)
> #165 bdelete when last win (E444)

- autoload/ctrlsf/backend.vim
- autoload/ctrlsf/opt.vim
Could not find a way to search for a string that started with a dash, for example `:CtrlSF -foo` so implemented the double dash option that's analogous to what's used by most commands, now you can search with `:CtrlSF -- -foo`. =)
> Add double dash option to support searching patterns that start with dash

- doc/ctrlsf.txt
ctrlsf_default_view_mode doc example I thought it's a typo?
> fix ctrlsf_default_view_mode doc example typo

- autoload/ctrlsf/opt.vim
if backend is rg, when invoke vim without file arguments, then
expand('%:p') will return empty string '', but rg will fail.
FAIL:    usr/bin/rg -C 5  --smart-case --fixed-strings --no-heading --color never --line-number -- 'cstring' ''
SUCCESS: usr/bin/rg -C 5  --smart-case --fixed-strings --no-heading --color never --line-number -- 'cstring'
> fix(bug): expand('%:p')

- README.md
- autoload/ctrlsf/backend.vim
- autoload/ctrlsf/opt.vim
- doc/ctrlsf.txt
Hi, thanks for the great plugin!
Most of the backend engines have a flag option to search only for whole words (-w) instead of wrapping the regex in word boundaries.
Not sure if I missed something but I did not find a way to forward flags from ctrlsf to the backend, I just saw a way to hardcode them permanently.
So I though that having such flag would be a good addition. Let me know if I can improve this or update the docs.
> Add flag to search only for words

- README.md
- autoload/ctrlsf/utils.vim
- doc/ctrlsf.txt
Allow passing suffix to ctrlsf buffer mappings. Useful for tasks like `zz` or `<C-w>p`. Eg:
```vimL
let g:ctrlsf_mapping = {
\ "open"    : ["<CR>", "o"],
\ "openb"   : { "key": "O", "suffix": "<C-w>p" },
\ "split"   : "<C-O>",
\ "vsplit"  : "",
\ "tab"     : "t",
\ "tabb"    : "T",
\ "popen"   : "p",
\ "popenf"  : "P",
\ "quit"    : "q",
\ "next"    : "<C-J>",
\ "prev"    : "<C-K>",
\ "pquit"   : "q",
\ "loclist" : "",
\ "chgmode" : "M",
\ }
```
Note this is fully backwards compatible with existing mappings. It merely adds the option to specify the value as: `{ "key": keyVal [, "suffix": suffixVal] }` where `keyVal` is a string or array, and `suffixVal` is a string.
Please let me know if this is something you'd be willing to merge so that I can update the docs.
> [WIP] Allow suffix in buffer maps

- autoload/ctrlsf/pat.vim
- doc/ctrlsf.txt
Preface
=====
I use rg as my backend, but ack backend has the same question.
1 test code
=======
I have a file name php.c, with this content in it.
```c
f.type = ZEND_OVERLOADED_FUNCTION
```
I try to find out '.type ='
and I use this Ex command to seach it, 
```vim
:CtrlSF -R \.type\s*=
```
BUT I get this error message
```vim
Error detected while processing function ctrlsf#Search[15]..<SNR>118_ExecSearch[23]..ctrlsf#db#ParseAckprgResult[44]..ctrlsf#class#paragraph#New[15]..ctrlsf#class#line#New:
line    1:
E871: (NFA regexp) Can't have a multi follow a multi !
E62: Nested =
```
1.1 error reproduce
---------------------
run this vim code
```vim
:echo match('f.type = ZEND_OVERLOADED_FUNCTION', '\v\.type\s*=')
```
,it will output the same error message
```vim
E871: (NFA regexp) Can't have a …
```
> vim-regex when magic is \v, '=' '&' is no literally, should change to '\=' and '\&'

- autoload/ctrlsf/win.vim
I've had this little annoyance from the start because I have _relativenumbers_ enabled, so I've always seen two line numbers in every line in the CtrlSF window.
This PR disables the abovementioned option locally.
> Hide line numbers when relativenumber is set

- autoload/ctrlsf/backend.vim
- doc/ctrlsf.txt
Hey since sometimes the rg backend does not recognize certain filetypes and adding a file-type see [this](https://github.com/BurntSushi/ripgrep/issues/118) is such a pain (because aliases are not that easy to be picked by vim). I thought it would be good to add GLOB support for ripgrep too. The syntax however is a wildcard one not a regex.
e.g. `:CtrlSF -G *.pug svg` will find svg in all pug files.
Didn't want to put example in the docs not to confuse fresh users, however users with non-default backend will understand how to type it.
Hope this makes sense.
Regards,
Petur
> Add -G support for ripgrep

- .gitignore
After running `:Helptags` vim creates untracked `doc/tags`. Ignore the file.
> .gitignore for swap, session, temp and generated files

- autoload/ctrlsf/backend.vim
Fix #195 .
Ag's behavior differs from what is documented in its manual for
option '--filename', it does not print filename even '--filename' is
specified.
With below command
```shell
$ ag -C 3 --smart-case --literal --noheading --nogroup --nocolor --nobreak --filename --follow -- 'foo' '.'
```
We get output like this
```
sample2
1:foo
2-bar
3-
sample1
1:foo
2-bar
3-
```
But what we need is
```
sample1:1:foo
sample1:2-bar
sample1:3-
sample2:1:foo
sample2:2-bar
sample2:3-
```
> Fix working with Ag

- autoload/ctrlsf/class/paragraph.vim
The solution is replacing` '\\'` with` '\'`.
e.g.,`'D:\\LeaderF\autoload\leaderf\bufExpl.py'`-> `'D:\LeaderF\autoload\leaderf\bufExpl.py'`
> fix issue #244

- autoload/ctrlsf/backend.vim
https://github.com/dyng/ctrlsf.vim/pull/251 introduced additional flags for enabling/disabling following symlinks. However there was a small mistake there: the flag for ripgrep is `--no-follow`.
Currently i see this:
```
Backend Failure. Error messages: error: Found argument '--nofollow' which wasn't expected, or isn't valid in this context                                                  
Backend Failure. Error messages: ^IDid you mean --no-follow?                                                                                                               
Backend Failure. Error messages:                                                                                                                                           
Backend Failure. Error messages: USAGE: …
```
> Fix no follow flag for ripgrep

- doc/ctrlsf.txt
- plugin/ctrlsf.vim
I think it's better to set `g:ctrlsf_follow_symlinks` by default, because many modern backend such as `rg` does so.
> Set 'g:ctrlsf_follow_symlinks' by default

- autoload/ctrlsf/win.vim
Previous restoring isnt work properly. That does'nt restore splits actualy. Only
align by "wincmd =".
> fix: save and restore splits by builtin features

- autoload/ctrlsf.vim
- autoload/ctrlsf/edit.vim
- autoload/ctrlsf/view.vim
- doc/ctrlsf.txt
A file whose name starts with number can't be recognized as a normal
Filename, then InconsistentException is raised. Fix #269 .
> Fix corrupted filename error

- autoload/ctrlsf/win.vim
Fix problem introduced in #264 .
The problem: open a preview window then close it, and then closing the main window can not restore all windows to their initial sizes.
> Save and restore windows size using stack

- autoload/ctrlsf/backend.vim
- autoload/ctrlsf/opt.vim
- doc/ctrlsf.txt
By default rg, ag and pt exclude hidden files and directories, this
introduces a new -hidden argument to include them.
> Introduce -hidden argument to search hidden files and directories

- autoload/ctrlsf/win.vim
With `g:ctrlsf_default_view_mode = 'compact'` if a search turns up with
no results the "Searching..." text will still be displayed in the
results window.
This commit makes it so that "Nothing found!" is shown instead.
**Before**
**After**
> Indicate nothing found in compact mode

- autoload/ctrlsf/async.vim
An issue exists where the timer id of an running async search is lost
if a new search is performed resulting in the timer never ending.
Here we make sure to cover multiple scenarios so that we don't lose a
timer.
> Fix async timer doesn't end

- README.md
- autoload/ctrlsf.vim
- doc/ctrlsf.txt
- plugin/ctrlsf.vim
I added an extra option, `g:ctrlsf_auto_preview` to enable auto-previewing while navigating in the
results pane. The default is 0, which doesn't modify the original behavior.
> Add auto_preview option

- README.md
- autoload/ctrlsf/opt.vim
- doc/ctrlsf.txt
As almost all commonly used arguments have shortcuts,
let's add a shortcut for '-filetype' as well.
> Add '-T' shortcut for '-filetype'

- autoload/ctrlsf/win.vim
https://github.com/dyng/ctrlsf.vim/issues/292 is caused by winrestcmd.
When columns or lines is changed, don't reset the window layout.
> fix resize terminal window cause a blank area

- autoload/ctrlsf/opt.vim
Searches such as `:CtrlSF -- -A` will fail with an "Unknow option"
error. This also fixes the issue where `:CtrlSF -- --` will execute a
search with an empty pattern.
> Fix setting a pattern that matches an option

- autoload/ctrlsf/fs.vim
In case when ctrlsf_extra_root_markers is higher in the directories hierarhy,
than any of vcs_markers, the search will be stopped earlier at one of vcs_marker.
This fix forces to do search by ctrlsf_extra_root_markers first and then
try vcs_markers if no root folder found.
> Fix ctrlsf_extra_root_markers

- autoload/ctrlsf/preview.vim
- autoload/ctrlsf/win.vim
- doc/ctrlsf.txt
- plugin/ctrlsf.vim
The g:ctrlsf_winsize variable only controls the non-compact CtrlSF,
therefore a new g:ctrlsf_compact_winsize config is introduced to control
the compact window in much the same way.
> Introduce g:ctrlsf_compact_winsize config variable

- README.md
- autoload/ctrlsf/preview.vim
- autoload/ctrlsf/win.vim
- doc/ctrlsf.txt
- plugin/ctrlsf.vim
This commit adds "left_local" and "right_local" as additional settings
for `g:ctrlsf_position`. These settings work like "left" and "right"
except that they open the CtrlSF window adjacent to the current window,
rather than on the edge of the tabpage. The commit also adds
documentation.
> Add "local" window position options.

- autoload/ctrlsf.vim
- autoload/ctrlsf/opt.vim
- doc/ctrlsf.txt
- plugin/ctrlsf.vim
`CtrlSFUpdate` could set arguments to override previous search
> support CtrlSFUpdate override search options
